### ISSUE TITLE
showAllValues not working with Custom results

### ISSUE THREAD

**Issue by ilbonte** [alphagov/accessible-autocomplete#554]
The options list is not showing when using custom results/tempaltes

Step to reproduce:
* clone the repo
* add to`showAllValues: true,` the custom result example (https://github.com/alphagov/accessible-autocomplete/blob/d892838bd2f634a4261a121eaa135cf1b502fc6b/examples/index.html#L515-L525)

Used the last version of this library on chrome on OSX

Is there a workaround to fix this behaviour?

**Comment by ilbonte** [comment]
I've also noticed that when I focus the input element and press the down arrow key I get an exception:
```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'focus')
    at e.t.componentDidUpdate (autocomplete.js:133:39)
    at V (preact.mjs:597:1)
    at f (preact.mjs:84:1)
t.componentDidUpdate @ autocomplete.js:133
V @ preact.mjs:597
f @ preact.mjs:84
Promise.then (async)
a @ preact.mjs:75
setState @ preact.mjs:690
(anonymous) @ autocomplete.js:319
customSuggest @ index.html:496
t.handleDownArrow @ autocomplete.js:318
t.handleKeyDown @ autocomplete.js:382
d @ preact.mjs:179
```
<img width="683" alt="image" src="https://user-images.githubusercontent.com/7412876/164668525-dea98d0c-2a84-4aca-a5b3-252c6227b92e.png">
